"""indexes, share expiry, trgm search

Revision ID: 32796543a937
Revises: c774e4ccd82a
Create Date: 2026-08-06 11:57:51.376835

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '32796543a937'
down_revision: str | Sequence[str] | None = 'c774e4ccd82a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_sessions_user_updated', 'chat_sessions', ['user_id', 'updated_at'], unique=False)
    op.create_index('ix_documents_user_uploaded', 'documents', ['user_id', 'uploaded_at'], unique=False)
    op.create_index('ix_fundamentals_market_cap', 'fundamentals', ['market_cap'], unique=False)
    op.create_index('ix_fundamentals_pe_ratio', 'fundamentals', ['pe_ratio'], unique=False)
    op.create_index('ix_fundamentals_sector', 'fundamentals', ['sector'], unique=False)
    op.create_index('ix_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False)
    op.add_column('share_tokens', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # Hand-written: trigram index so /api/chat/search's ILIKE '%q%' uses an
    # index scan instead of seq-scanning every message the user has ever sent.
    # (pg_trgm ships with Postgres; CREATE EXTENSION needs a role that owns
    # the DB — true for the app role in dev/CI/prod compose setups.)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_messages_content_trgm "
        "ON messages USING gin (content gin_trgm_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_messages_content_trgm")
    op.drop_column('share_tokens', 'expires_at')
    op.drop_index('ix_messages_session_created', table_name='messages')
    op.drop_index('ix_fundamentals_sector', table_name='fundamentals')
    op.drop_index('ix_fundamentals_pe_ratio', table_name='fundamentals')
    op.drop_index('ix_fundamentals_market_cap', table_name='fundamentals')
    op.drop_index('ix_documents_user_uploaded', table_name='documents')
    op.drop_index('ix_chat_sessions_user_updated', table_name='chat_sessions')
    # ### end Alembic commands ###
