"""share_tokens, personas, oauth_tokens, session persona

Revision ID: c774e4ccd82a
Revises: 2a6d4efd8caa
Create Date: 2026-08-06 09:02:39.526858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c774e4ccd82a'
down_revision: Union[str, Sequence[str], None] = '2a6d4efd8caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('personas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_user_id'), 'personas', ['user_id'], unique=False)
    op.create_table('share_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_tokens_session_id'), 'share_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_share_tokens_user_id'), 'share_tokens', ['user_id'], unique=False)
    # (checkpoint-table drops that autogenerate emitted here were removed —
    # those tables are runtime-owned by LangGraph; see alembic/env.py filter.)
    op.add_column('chat_sessions', sa.Column('persona_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'personas', ['persona_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # None → Postgres default constraint name, matching what upgrade() created.
    op.drop_constraint('chat_sessions_persona_id_fkey', 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'persona_id')
    op.drop_index(op.f('ix_share_tokens_user_id'), table_name='share_tokens')
    op.drop_index(op.f('ix_share_tokens_session_id'), table_name='share_tokens')
    op.drop_table('share_tokens')
    op.drop_index(op.f('ix_personas_user_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_table('oauth_tokens')
    # ### end Alembic commands ###
